complete_from_path = true
ctrlc_exit = false
disable_table_indexes = false
filesize_format = "B"
filesize_metric = true
nonzero_exit_errors = true
pivot_mode = "auto"
plugin_dirs = ["D:\\Src\\GitHub\\nu-plugin-lib\\samples\\Nu.Plugin.Len\\bin\\Debug\\netcoreapp3.1"]
prompt = "build-string (ansi ub) '╭─( ' (ansi rb) (date format '%I:%M:%S:%p') (ansi reset) (ansi ub) ' )─╮\n╰─○ ' "
rm_always_trash = true
skip_welcome_message = true
startup = ["clear", "alias show = cat ", "alias dev = fzf --layout=reverse-list --inline-info --prompt='[Irfan@Dev]:~# ' --marker='▶' --pointer='▶' ", "alias irfan = fd", "alias neofetch = neofetch --ascii_distro Manjaro --ascii_colors 4 --ascii_bold on ",  "alias la = ls --long", "def nudown [] {fetch https://api.github.com/repos/nushell/nushell/releases | get assets | select name download_count}", "def nuver [] {version | pivot key value}", "alias nuopen = open", "alias open = open", "alias fzf = dev"]
table_mode = "pager"

[color_config]
header_align = "left"
header_bold = true
separator_color = "ub"
[line_editor]
auto_add_history = true
bell_style = "audible"
color_mode = "enabled"
completion_prompt_limit = 100
completion_type = "circular"
edit_mode = "emacs"
history_duplicates = "ignoreconsecutive"
history_ignore_space = false
keyseq_timeout_ms = 500
max_history_size = 100000
tab_stop = 4

[textview]
HOME = "$HOME"
SHELL = "~/../usr/bin/zsh"
USER = "tegardev"
ZSH = "~/.oh-my-zsh"
colored_output = true
grid = false
header = true
line_numbers = true
pager = "less"
paging_mode = "QuitIfOneScreen"
snip = true
tab_width = 4
term_width = "default"
theme = "TwoDark"
true_color = true
use_italics = true
vcs_modification_markers = true
wrapping_mode = "Character"
